name: docker build container

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  docker-build-container:
    runs-on: ubuntu-latest
    steps:
      - name: build docker image
        uses: senzing-factory/github-action-docker-buildx-build@v2
        with:
          image-repository: senzing/cognito-authorizer
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
